name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Cache node modules @ website
      uses: actions/cache@v1
      id: cache-website
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/website/yarn.lock') }}
    - name: Cache node modules @ example
      uses: actions/cache@v1
      id: cache-example
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/example/yarn.lock') }}
    - name: Instal dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
    - name: Instal dependencies @ website
      if: steps.cache-website.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --cwd ./website
    - name: Instal dependencies @ example
      if: steps.cache-example.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --cwd ./example

  test:
    runs-on: ubuntu-latest
    needs: build
    run: |
      yarn run lint
      yarn run flow
